### ISSUE TITLE
Not working in windows or with windows paths?

### ISSUE THREAD

**Issue by ajflash** [gilmarsquinelato/vscode-architect#5]
Hi,

I found your module interesting. Thanks. 
I've tried to test it in one of my project files and it did not show anything. I have no knowledge about vscode plug-in development but looking at the vscode console output for any issues it seems that it is not recognizing the paths in some way (the absolute path to the file being analyzed):

![image](https://user-images.githubusercontent.com/2129987/59218651-06c47c80-8bc1-11e9-8b42-922c8b8c87eb.png)

**Comment by gilmarsquinelato** [comment]
Hi @ajflash, thanks for reporting this bug.
I found what was wrong, fixed it and is available now at v0.1.0.

Thanks!
